### PR TITLE
libtss2-mu bindings

### PR DESCRIPTION
**Pull request by whooo**
Adds the bindings for libtss2-mu and attach them to the different objects.

Fixes https://github.com/tpm2-software/tpm2-pytss/issues/57

### CODE REVIEW

**Comment by whooo** [comment]
I'm not really sure why the DOCS test fails, everything I committed looks to be ascii only.

**Comment by williamcroberts** [comment]
> I'm not really sure why the DOCS test fails, everything I committed looks to be ascii only.

I don;t understand it either, I ran ./scripts/docs.sh locally and it worked fine.

**Comment by williamcroberts** [comment]
I want this, LGTM. As far as that DOCS error, let me get @pdxjohnny to look at it. This also affects my PR:
  - https://github.com/tpm2-software/tpm2-pytss/pull/78

I'm not sure why it's griping, local runs seem fine.

**Comment by williamcroberts** [comment]
@whooo I solved it, its on master. Please rebase and force push.

**Review by williamcroberts — APPROVED** [review]

**Pull request merged**
