### PR TITLE
CHANGELOG: update for 1.3.0-rc0

### PR DESCRIPTION
**Pull request by williamcroberts**
Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Comment by williamcroberts** [comment]
@whooo I think we trim the CI builds down after the 1.3.0 release?

I'm not too worried about tss2-policy API changing on master, 4.0 will be released later but I figured no reason to really hold up the release train on that?

**Comment by williamcroberts** [comment]
> I'm not too worried about tss2-policy API changing on master, 4.0 will be released later but I figured no reason to really hold up the release train on that?

Policy tests are running against master:
  - https://github.com/tpm2-software/tpm2-pytss/actions/runs/3363519002/jobs/5576776615#step:5:1189

**Comment by whooo** [comment]
@williamcroberts  I don't really see any reason to hold up the release until 4.0 is released neither, I have some small fixes as well as https://github.com/tpm2-software/tpm2-pytss/issues/372 that I would like to see in the 1.3.0. I'll probably be able to fix those during the week.

**Comment by williamcroberts** [comment]
> @williamcroberts I don't really see any reason to hold up the release until 4.0 is released neither, I have some small fixes as well as #372 that I would like to see in the 1.3.0. I'll probably be able to fix those during the week.

@whooo I am still holding this release, but I figured id update the PR just to let the CI trigger. We're down to 2 PRs/Bugs for the 4.0 tpm2-tss release and 1 for the 3.2.1 milestone. So we're getting close over there :-P.

**Comment by williamcroberts** [comment]
Version is moving to 2.0

**Pull request closed without merging**
