### PR TITLE
Skip test using P-192 when not available

### PR DESCRIPTION
**Pull request by Jakuje**
and fix the typo in the curve name in other places this is used.

### CODE REVIEW

**Comment by whooo** [comment]
Just so I know, is this related to missing ECC curves in some distributions (due to patents)?

**Comment by Jakuje** [comment]
I do not know all the background, but the reason for excluding the P-192 I remember was that its too small to be secure.

Fedora spec file is not much more verbose either:

https://src.fedoraproject.org/rpms/openssl/blob/rawhide/f/openssl.spec#_65

**Comment by whooo** [comment]
You should be able to switch to another curve available in the openssl/cryptography, the check is done on cryptography types, so the curve doesn't need to be available in the TPM simulator

**Comment by Jakuje** [comment]
Indeed! You are right. This fails early before getting to the tpm2 so we could use any other that should be widely available, such as `ec.SECP384R1`. Let see if it will work in all the cases. Verified it works on Fedora rawhide (in mock).

**Comment by whooo** [comment]
The build error is fixed on master now, could you rebase and push?

**Comment by Jakuje** [comment]
Reran, but there is still some likely intermittent failure.

**Review by whooo — APPROVED** [review]

**Comment by whooo** [comment]
Thanks for your continuing contributions!

**Pull request merged**
